# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test CI

on:
  push:
    branches: [herokuDeployTest]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          PORT: ${{secrets.PORT}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          LOCAL_URL: ${{secrets.LOCAL_URL}}
          TEST_DB: ${{secrets.TEST_DB}}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sharpsback"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_PORT: ${{secrets.PORT}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_PUBLIC_URL: ${{secrets.PUBLIC_URL}}
          HD_PUBLIC_DB: ${{secrets.PUBLIC_DB}}
